final products = [
  {
    'id': '0',
    'title': 'Men\'s Nike Air Max',
    'price': 44.52,
    // 'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '1',
    'title': 'Adidas Ultraboost',
    'price': 89.99,
    // 'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Adidas',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '2',
    'title': 'Bata Women\'s Comfy Walk',
    'price': 35.95,
    // 'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Bata',
    'sizes': [6, 7, 8, 9],
  },
  {
    'id': '3',
    'title': 'Air Jordan 1 Retro',
    'price': 399.99,
    // 'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '4',
    'title': 'Women\'s Nike Zoom',
    'price': 79.99,
    // 'imageUrl': 'assets/images/shoes_5.png',
    'company': 'Nike',
    'sizes': [6, 7, 8, 9],
  },
  {
    'id': '5',
    'title': 'Adidas Superstar Classic',
    'price': 75.00,
    // 'imageUrl': 'assets/images/shoes_6.png',
    'company': 'Adidas',
    'sizes': [7, 8, 9, 10],
  },
  {
    'id': '6',
    'title': 'Bata Men\'s Office Wear',
    'price': 45.99,
    // 'imageUrl': 'assets/images/shoes_7.png',
    'company': 'Bata',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '7',
    'title': 'Air Jordan 4 Premium',
    'price': 450.00,
    // 'imageUrl': 'assets/images/shoes_8.png',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '8',
    'title': 'Adidas NMD Runner',
    'price': 129.99,
    // 'imageUrl': 'assets/images/shoes_9.png',
    'company': 'Adidas',
    'sizes': [7, 8, 9, 10],
  },
  {
    'id': '9',
    'title': 'Bata Kids Sport',
    'price': 29.99,
    // 'imageUrl': 'assets/images/shoes_10.png',
    'company': 'Bata',
    'sizes': [3, 4, 5, 6],
  },
  {
    'id': '10',
    'title': 'Nike Air Force 1',
    'price': 110.00,
    // 'imageUrl': 'assets/images/shoes_11.png',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '11',
    'title': 'Adidas Gazelle',
    'price': 85.00,
    // 'imageUrl': 'assets/images/shoes_12.png',
    'company': 'Adidas',
    'sizes': [7, 8, 9, 10],
  },
  {
    'id': '12',
    'title': 'Bata Casual Sneakers',
    'price': 39.99,
    // 'imageUrl': 'assets/images/shoes_13.png',
    'company': 'Bata',
    'sizes': [8, 9, 10],
  },
  {
    'id': '13',
    'title': 'Jordan 11 Retro',
    'price': 375.00,
    // 'imageUrl': 'assets/images/shoes_14.png',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '14',
    'title': 'Adidas Stan Smith',
    'price': 95.00,
    // 'imageUrl': 'assets/images/shoes_15.png',
    'company': 'Adidas',
    'sizes': [7, 8, 9, 10],
  },
  {
    'id': '15',
    'title': 'Nike SB Dunk Low',
    'price': 299.99,
    // 'imageUrl': 'assets/images/shoes_16.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': '16',
    'title': 'Adidas Yeezy Boost',
    'price': 499.99,
    // 'imageUrl': 'assets/images/shoes_17.png',
    'company': 'Adidas',
    'sizes': [7, 8, 9, 10],
  },
  {
    'id': '17',
    'title': 'Bata Formal Collection',
    'price': 55.00,
    // 'imageUrl': 'assets/images/shoes_18.png',
    'company': 'Bata',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '18',
    'title': 'Nike Blazer Mid',
    'price': 115.00,
    // 'imageUrl': 'assets/images/shoes_19.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': '19',
    'title': 'Adidas Forum Low',
    'price': 90.00,
    // 'imageUrl': 'assets/images/shoes_20.png',
    'company': 'Adidas',
    'sizes': [7, 8, 9, 10],
  },
];

final cart = [
  {
    'id': '19',
    'title': 'Adidas Forum Low',
    'price': 90.00,
    // 'imageUrl': 'assets/images/shoes_20.png',
    'company': 'Adidas',
    'sizes': [7, 8, 9, 10],
  },
];